name: Build JavaFX Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23.0.1'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies and build the project
      - name: Build with Maven
        run: mvn clean package

      # Create the executables folder and move the JAR file
      - name: Move JAR to executables folder
        run: |
          mkdir -p executables
          mv target/*.jar executables/

      # Push the executables folder to the repository
      - name: Commit and push executables folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add executables/
          git commit -m "Add generated JAR files to executables folder"
          git push

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.0
          releaseName: "JavaFX Application v1.0.0"
          draft: false
          prerelease: false
          artifacts: executables/*.jar